#!/usr/bin/env bash
#
# Restart service.

shopt -s inherit_errexit
set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091
source utils.sh

fancy_echo "Restarting service"
sudo service gitlab-runner.service restart
