#!/usr/bin/env bash
#
# Start service.

shopt -s inherit_errexit
set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091
source utils.sh

fancy_echo "Starting service"
sudo service gitlab-runner start
